# Miarka reference registry for neville_mx_amplicon
reference:
  fasta:
    path: neville/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta
    url: file:/proj/ngi2024001/nobackup/bin/wp2_neville/design_and_ref_files/neville/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta
  fai:
    path: neville/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.fai
    url: file:/proj/ngi2024001/nobackup/bin/wp2_neville/design_and_ref_files/neville/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.fai
  sequence_dict:
    path: neville/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.dict
    url: file:/proj/ngi2024001/nobackup/bin/wp2_neville/design_and_ref_files/neville/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.dict
  design_bed:
    path: neville/bedfiles/amplicons.bed
    url: file:/proj/ngi2024001/nobackup/bin/wp2_neville/design_and_ref_files/neville/bedfiles/amplicons.bed
  design_intervals:
    path: neville/bedfiles/amplicons.interval_list
    url: file:/proj/ngi2024001/nobackup/bin/wp2_neville/design_and_ref_files/neville/bedfiles/amplicons.interval_list
  vep_cache:
    path: neville/VEP
    url: file:/proj/ngi2024001/nobackup/bin/wp2_neville/design_and_ref_files/neville/VEP
