---
output: "config/output_files.yaml"
resources: "{{resources}}"
samples: "config/samples.tsv"
units: "config/units.tsv"
samples_run: "samples.tsv"
units_run: "units.tsv"

# Custom keys and values below

proj_data: "{{proj_data}}"
ref_data: "{{ref_fasta}}"
bed_files: "{{bed_files}}"
reference:
  design_intervals: "{{ref_design_intervals}}"
  fasta: "{{ref_fasta}}"
  fai: "{{ref_fai}}"
  sequence_dict: "{{ref_sequence_dict}}"
  design_bed: "{{ref_design_bed}}"

# All runs
runfolder: "{{runfolder}}"
batchid: "{{batchid}}"
runid: "{{runid}}"
multisample: "{{multisample}}"
samplesheet: "{{samplesheet}}"
raw_data: "pod5"

dorado_model: "dna_r10.4.1_e8.2_400bps_sup@v5.2.0"

amplicons:
  ["FLT3_ITD_3kb_1", "FLT3_TKD_3kb_1",
  "IDH1_1", "IDH2_1",
  "NPM1_5",
  "TP53_3kb_A1", "TP53_3kb_B1", "TP53_C10", "TP53_J3", "TP53_D2", "TP53_E1", "TP53_F2", "TP53_G4", "TP53_H4", "TP53_I4"
  ]

extra_regions:
  ["TP53_3kb_A1_only", "TP53_3kb_B1_only", "TP53_C10_only", "TP53_D2+J3", "TP53_D2_only",
  "TP53_E1_only", "TP53_F2_only", "TP53_G4_only", "TP53_H4_only", "TP53_I4_only"
  ]

pools:
  1: ["TP53_3kb_A1_only", "TP53_D2_only", "TP53_F2_only", "TP53_I4_only", "FLT3_TKD_3kb_1"]
  2: ["IDH1_1", "TP53_3kb_B1_only", "TP53_G4_only", "TP53_D2+J3", "NPM1_5"]
  3: ["IDH2_1", "TP53_C10_only", "TP53_E1_only", "TP53_H4_only", "FLT3_ITD_3kb_1"]


# Containers

default_container: "{{HYDRAGENETICS_PREFIX}}/common{{CONTAINER_SUFFIX}}3.0.0{{CONTAINER_EXT}}"

bcbio_variation_recall_ensemble:
  container: "{{HYDRAGENETICS_PREFIX}}/bcbio-vc{{CONTAINER_SUFFIX}}0.2.6{{CONTAINER_EXT}}"
  callers:
    - clairs_to
    - deepsomatic
    - vardict
  support: 1

bcftools_view:
  filter:
    deepsomatic:
      extra: "-i 'QUAL>0'"
    clairs_to:
      extra: "-e 'FILTER==\"LowQual\" & QUAL==0'"
    vardict:
      extra: "-i 'QUAL>120'"
    sniffles2:
      extra: "-R {{bed_files}}/amplicons-sniffles2.bed"

clairs_to:
  container: "{{HKUBAL_PREFIX}}/clairs-to{{CONTAINER_SUFFIX}}latest{{CONTAINER_EXT}}"
  platform: "ont_r10_dorado_sup_5khz"
  snv_min_af: 0.005
  indel_min_af: 0.005
  bed_file: "{{bed_files}}/amplicons-clairs-to.bed"

deepsomatic:
  container: "{{GOOGLE_PREFIX}}/deepsomatic{{CONTAINER_SUFFIX}}1.9.0{{CONTAINER_EXT}}"
  extra: '--make_examples_extra_args="vsc_min_fraction_snps=0.01,vsc_min_fraction_indels=0.01,small_model_snp_gq_threshold=20,small_model_indel_gq_threshold=20"'
  # filter: '--use_default_pon_filtering=true --qual_filter=0.1'
  bed_file: "{{bed_files}}/amplicons-exons-deepsomatic.bed"

dorado:
  container: "{{ONTRESEARCH_PREFIX}}/dorado{{CONTAINER_SUFFIX}}latest{{CONTAINER_EXT}}"

dorado_align:
  container: "{{ONTRESEARCH_PREFIX}}/dorado{{CONTAINER_SUFFIX}}latest{{CONTAINER_EXT}}"
  # extra: '--mm2-opts "-x sr"' # "-x sr": alignment for short-read data without splicing (from gDNA), otherwise default "-x lr:hq" preset for ONT long-read

dorado_basecaller:  # simplex basecalling by default
  container: "{{ONTRESEARCH_PREFIX}}/dorado{{CONTAINER_SUFFIX}}latest{{CONTAINER_EXT}}"
  model: "dna_r10.4.1_e8.2_400bps_sup@v5.2.0"
  trim: "--trim adapters"
  extra: "--device cuda:all"

dorado_demux:
  container: "{{ONTRESEARCH_PREFIX}}/dorado{{CONTAINER_SUFFIX}}latest{{CONTAINER_EXT}}"
  kit: "--kit-name SQK-NBD114-24"

dorado_duplex:
  container: "{{ONTRESEARCH_PREFIX}}/dorado{{CONTAINER_SUFFIX}}latest{{CONTAINER_EXT}}"
  model: "dna_r10.4.1_e8.2_400bps_sup@v5.2.0"
  trim: "--no-trim-primers --sequencing-kit SQK-LSK114"
  extra: "--device cuda:all"

dorado_duplex_multisamples:
  container: "{{ONTRESEARCH_PREFIX}}/dorado{{CONTAINER_SUFFIX}}latest{{CONTAINER_EXT}}"
  model: "dna_r10.4.1_e8.2_400bps_sup@v5.2.0"
  trim: ""  # no trim because samples are demultiplexed in a later step
  extra: "--device cuda:all"

dorado_trim:
  container: "{{ONTRESEARCH_PREFIX}}/dorado{{CONTAINER_SUFFIX}}latest{{CONTAINER_EXT}}"
  trim: "--sequencing-kit SQK-NBD114-24"

filter_vcf:
  somatic_soft: "config/config_soft_filter_somatic.yaml"
  somatic_hard: "config/config_hard_filter_somatic.yaml"

filtlong:
  container: "{{HYDRAGENETICS_PREFIX}}/filtlong{{CONTAINER_SUFFIX}}0.2.1{{CONTAINER_EXT}}"
  min_length: 2000
  max_length: 4000

mosdepth:
  container: "{{HYDRAGENETICS_PREFIX}}/mosdepth{{CONTAINER_SUFFIX}}0.3.6{{CONTAINER_EXT}}"
  by: "amplicons.bed"

mosdepth_bed:
  container: "{{HYDRAGENETICS_PREFIX}}/mosdepth{{CONTAINER_SUFFIX}}0.3.6{{CONTAINER_EXT}}"
  thresholds: "1,5,100,500,1000"

mosdepth_exons:
  container: "{{HYDRAGENETICS_PREFIX}}/mosdepth{{CONTAINER_SUFFIX}}0.3.6{{CONTAINER_EXT}}"
  bed: "exon_coverage.bed"
  thresholds: "1,5,100,500,1000"

multiqc:
  container: "{{HYDRAGENETICS_PREFIX}}/multiqc{{CONTAINER_SUFFIX}}1.25.1{{CONTAINER_EXT}}" # sequali requires 1.25.1, fixes for HsMetrics require 1.21
  reports:
    amplicons:
      config: "config/multiqc_config.yaml"
      qc_files:
        - "results/sequali/{experiment}_{sample}_{type}_reads.ont_adapt_trim.filtered.fastq.gz.json"
        - "results/sequali/{experiment}_{sample}_{type}_reads.ont_adapt_trim.filtered.fastq.gz.html"
        - "results/sequali/{experiment}_{sample}_{type}_reads.ont_adapt_trim.filtered.out.fastq.gz.json"
        - "results/sequali/{experiment}_{sample}_{type}_reads.ont_adapt_trim.filtered.out.fastq.gz.html"
        - "results/pycoqc/{experiment}_{sample}_{type}_report_sequencing_summary.json"
        - "prealignment/filtlong/{experiment}_{sample}_{type}.filtlong.log"
        - "results/mosdepth/{experiment}_{sample}_{type}_amplicons.regions.bed.gz"
        - "results/mosdepth/{experiment}_{sample}_{type}_amplicons.mosdepth.global.dist.txt"
        - "results/mosdepth/{experiment}_{sample}_{type}_amplicons.mosdepth.region.dist.txt"
        - "results/mosdepth/{experiment}_{sample}_{type}_amplicons.mosdepth.summary.txt"
        - "results/mosdepth_bed/{experiment}_{sample}_{type}_{target}.mosdepth.summary.txt"
        - "results/mosdepth_bed/{experiment}_{sample}_{type}_{target}.mosdepth.region.dist.txt"
        - "results/mosdepth_bed/{experiment}_{sample}_{type}_{target}.regions.bed.gz"
        - "results/mosdepth_bed/{experiment}_{sample}_{type}_{target}.per-base.bed.gz"
        - "results/mosdepth_bed/{experiment}_{sample}_{type}_{target}.thresholds.bed.gz"
        - "results/qc/samtools_ampliconclip/{experiment}_{sample}_{type}_ampliconclip.txt"
        - "results/qc/picard/{experiment}_{sample}_{type}_HsMetrics.txt"
        - "results/qc/picard/{experiment}_{sample}_{type}_{target}.alignment_summary_metrics.txt"
        - "results/qc/picard/{experiment}_{sample}_{type}_TP53_J3_only.alignment_summary_metrics.txt"
        - "results/qc/picard/{experiment}_{sample}_{type}.alignment_summary_metrics.txt"

gatk_mutect2:
  container: "{{HYDRAGENETICS_PREFIX}}/gatk4{{CONTAINER_SUFFIX}}4.6.2.0{{CONTAINER_EXT}}"

picard_collect_hs_metrics:
  container: "{{HYDRAGENETICS_PREFIX}}/picard{{CONTAINER_SUFFIX}}2.25.4{{CONTAINER_EXT}}"

picard_bed_to_interval_list:
  container: "{{HYDRAGENETICS_PREFIX}}/picard{{CONTAINER_SUFFIX}}2.25.4{{CONTAINER_EXT}}"

picard_collect_alignment_summary_metrics:
  container: "{{HYDRAGENETICS_PREFIX}}/picard{{CONTAINER_SUFFIX}}2.25.4{{CONTAINER_EXT}}"

plot_yield_timestep:
  container: "{{HYDRAGENETICS_PREFIX}}/common-plots{{CONTAINER_SUFFIX}}3.1.1{{CONTAINER_EXT}}"

pycoqc:
  container: "{{NANOZOO_PREFIX}}/pycoqc{{CONTAINER_SUFFIX}}2.5.0.23--320ecc7{{CONTAINER_EXT}}"

samtools:
  container: "{{HYDRAGENETICS_PREFIX}}/samtools{{CONTAINER_SUFFIX}}1.21{{CONTAINER_EXT}}"

savana:
  container: "{{HYDRAGENETICS_PREFIX}}/savana{{CONTAINER_SUFFIX}}1.3.5{{CONTAINER_EXT}}"

scanitd:
  bed_file: "-t {{bed_files}}/NPM1-FLT3-vardict.bed"
  extra: "--ao 3 --aln-mismatches 5 --ins-mismatches 7"
  container: "{{HYDRAGENETICS_PREFIX}}/scanitd{{CONTAINER_SUFFIX}}0.9.2{{CONTAINER_EXT}}"

sequali:
  container: "{{HYDRAGENETICS_PREFIX}}/sequali{{CONTAINER_SUFFIX}}0.12.0{{CONTAINER_EXT}}"

sniffles2_call:
  container: "{{HYDRAGENETICS_PREFIX}}/sniffles2{{CONTAINER_SUFFIX}}2.6.1{{CONTAINER_EXT}}"
  extra: "--minsvlen 3"
  # bed_file: Sniffles2 cannot be restricted to specific regions, variant filtering is required post-calling

vardict:
  container: "{{HYDRAGENETICS_PREFIX}}/vardict{{CONTAINER_SUFFIX}}1.8.3{{CONTAINER_EXT}}"
  allele_frequency_threshold: "0.002"
  extra: "-k 0 -L 1000 -a 50:0.95"
  bed_file: "{{bed_files}}/NPM1-FLT3-vardict.bed"
  bed_columns: "-c 1 -S 2 -E 3 -g 4"
  threads: 20

vep:
  container: "{{HYDRAGENETICS_PREFIX}}/vep{{CONTAINER_SUFFIX}}111.0{{CONTAINER_EXT}}"
  vep_cache: "{{ref_vep_cache}}"
  mode: "--offline --cache --merged "
  extra: " --format vcf --assembly GRCh38 --check_existing --pick --variant_class --everything  --pick_order mane_select,mane_plus_clinical,canonical,biotype,rank,appris,tsl,ccds,length,ensembl,refseq"

vt_decompose:
  container: "{{HYDRAGENETICS_PREFIX}}/vt{{CONTAINER_SUFFIX}}2015.11.10{{CONTAINER_EXT}}"

vt_normalize:
  container: "{{HYDRAGENETICS_PREFIX}}/vt{{CONTAINER_SUFFIX}}2015.11.10{{CONTAINER_EXT}}"

# Modules

modules:
  qc: "v0.5.0"  # "a5e356d": commit hash which is compatible with long-read units.tsv files, otherwise use "v0.5.0"

# rindels:
#   bin: "bin/rindels"
#   extra: "--ont"

# rs_qc:
#   bin: "bin/rs-qc"
