samples_ref: samples.tsv # only samples to include in panels
units_ref: units.tsv # only units to include in panels
panel_ref: panel_ref.tsv
resources_references: "config/resources_references.yaml"
output: "config/output_files_references.yaml"

default_container: docker://hydragenetics/common:3.0.0

reference_rules_snv_indels_deepsomatic_gvcf:
  container: "docker://google/deepsomatic:1.9.0"
  extra: '--make_examples_extra_args="vsc_min_fraction_snps=0.01,vsc_min_fraction_indels=0.01,small_model_snp_gq_threshold=20,small_model_indel_gq_threshold=20"'
  # filter: '--use_default_pon_filtering=true --qual_filter=0.1'
  bed_file: "/beegfs-storage/projects/wp4/nobackup/workspace/camille_test/ampliconthemato/bedfiles/M5-6-7/amplicons-background.bed"

reference_rules_snv_indels_clairs_to_gvcf:
  container: "docker://hkubal/clairs-to:latest"
  platform: "ont_r10_dorado_sup_5khz"
  snv_min_af: 0.005
  indel_min_af: 0.005
  bed_file: "/beegfs-storage/projects/wp4/nobackup/workspace/camille_test/ampliconthemato/bedfiles/M5-6-7/amplicons-background.bed"

reference_rules_snv_indels_vardict_gvcf:
  container: "docker://hydragenetics/vardict:1.8.3"
  allele_frequency_threshold: "0.002"
  extra: "-k 0 -L 1000 -a 50:0.95"
  bed_file: "/beegfs-storage/projects/wp4/nobackup/workspace/camille_test/ampliconthemato/bedfiles/M5-6-7/amplicons-background.bed"
  bed_columns: "-c 1 -S 2 -E 3 -g 4"
  threads: 20

create_background_file:
  min_dp: 300
  min_af: 0.03
