samples_ref: samples.tsv # only samples to include in panels
units_ref: units.tsv # only units to include in panels
panel_ref: panel_ref.tsv
resources_references: "config/resources_references.yaml"
output: "config/output_files_references.yaml"

default_container: docker://hydragenetics/common:3.0.0

reference_rules_snv_indels_deepsomatic_gvcf:
  container: "docker://google/deepsomatic:1.9.0"
  extra: '--make_examples_extra_args="vsc_min_fraction_snps=0.01,vsc_min_fraction_indels=0.01,small_model_snp_gq_threshold=20,small_model_indel_gq_threshold=20"'
  # filter: '--use_default_pon_filtering=true --qual_filter=0.1'
  bed_file: "/beegfs-storage/projects/wp4/nobackup/workspace/camille_test/ampliconthemato/bedfiles/M5-6-7/amplicons-background.bed"

create_background_file:
  min_dp: 300
  min_af: 0.03
