directory: ./reference_files

files:

  - name: "background file clairs-to"
    input: "references/create_background_file/background_panel_clairs_to.tsv"
    output: "background_panel_clairs_to.tsv"

  - name: "background file deepsomatic"
    input: "references/create_background_file/background_panel_deepsomatic.tsv"
    output: "background_panel_deepsomatic.tsv"

  - name: "background file vardict"
    input: "references/create_background_file/background_panel_vardict.tsv"
    output: "background_panel_vardict.tsv"

  - name: "artifact file"
    input: "references/create_artifact_file/artifact_panel.tsv"
    output: "artifact_panel.tsv"

  - name: "snv_indels_var_calls_ensembled_annotated_soft_filtered"
    output: "{experiment}_{sample}_{type}.ont_reads.snv-indels.vcf.gz"
    input: "snv_indels/bcbio_variation_recall_ensemble/{experiment}_{sample}_{type}.ensembled.vep_annotated.rename_vaf.filter.somatic_soft.vcf.gz"

  - name: "snv gVCF from clairs-to"
    input: "references/clairs_to/{experiment}_{sample}_{type}/{experiment}_{sample}_{type}_snv.g.vcf.gz"
    output: "{experiment}_{sample}_{type}_snv.clairs_to.g.vcf.gz"

  - name: "snv gVCF from deepsomatic"
    input: "references/deepsomatic/{experiment}_{sample}_{type}_reads.ont_adapt_trim.filtered.aligned.sorted.soft-clipped.deepsomatic.g.vcf.gz"
    output: "{experiment}_{sample}_{type}.deepsomatic.g.vcf.gz"

  - name: "gVCF from vardict"
    input: "references/vardict/{experiment}_{sample}_{type}_reads.ont_adapt_trim.filtered.aligned.sorted.soft-clipped.vardict.g.vcf.gz"
    output: "{experiment}_{sample}_{type}.vardict.g.vcf.gz"

  - name: "soft_clipped_bam"
    output: "Results/Data/{experiment}_{sample}_{type}.ont_reads.filtered.aligned.sorted.soft-clipped.bam"
    input: "alignment/dorado_align/{experiment}_{sample}_{type}_reads.ont_adapt_trim.filtered.aligned.sorted.soft-clipped.bam"

  - name: "soft_clipped_bam_bai"
    output: "Results/Data/{experiment}_{sample}_{type}.ont_reads.filtered.aligned.sorted.soft-clipped.bam.bai"
    input: "alignment/dorado_align/{experiment}_{sample}_{type}_reads.ont_adapt_trim.filtered.aligned.sorted.soft-clipped.bam.bai"