---

default_resources:
  threads: 1
  time: "12:00:00"
  mem_mb: 6144
  mem_per_cpu: 6144
  partition: "core"

alignment_ont_bam_index:
  partition: "core"
  time: "00:15:00"
  threads: 1
  mem_mb: 6144
  mem_per_cpu: 6144

alignment_ont_bam_softclip:
  partition: "core"
  time: "00:15:00"
  threads: 1
  mem_mb: 6144
  mem_per_cpu: 6144

alignment_ont_bam_sort:
  partition: "core"
  time: "00:15:00"
  threads: 1
  mem_mb: 6144
  mem_per_cpu: 6144

alignment_ont_dorado_align:
  partition: "core"
  time: "00:45:00"
  threads: 20
  mem_mb: 122880
  mem_per_cpu: 6144

alignment_ont_split_bam_by_target:
  partition: "core"
  time: "00:15:00"
  threads: 1
  mem_mb: 6144
  mem_per_cpu: 6144

alignment_ont_split_bam_target_j3:
  partition: "core"
  time: "00:15:00"
  threads: 1
  mem_mb: 6144
  mem_per_cpu: 6144

basecalling_bam_to_fastq:
  partition: "core"
  time: "00:15:00"
  threads: 1
  mem_mb: 6144
  mem_per_cpu: 6144

basecalling_compress_fastq:
  partition: "core"
  time: "00:15:00"
  threads: 1
  mem_mb: 6144
  mem_per_cpu: 6144

basecalling_dorado_basecaller:
  partition: "gpu"
  time: "72:00:00"
  gres: "--gres=gpu:l40s:3"
  threads: 32
  mem_mb: 192000
  mem_per_cpu: 6000

basecalling_dorado_duplex:
  partition: "gpu"
  time: "72:00:00"
  gres: "--gres=gpu:l40s:3"
  threads: 32
  mem_mb: 192000
  mem_per_cpu: 6000

basecalling_dorado_duplex_multisamples:
  partition: "gpu"
  gres: "--gres=gpu:a100:2"
  threads: 48
  mem_mb: 240000
  mem_per_cpu: 5000

basecalling_dorado_demux:
  partition: "core"
  time: "00:45:00"
  threads: 20
  mem_mb: 122880
  mem_per_cpu: 6144

prealignment_ont_filtlong:
  partition: "core"
  time: "00:25:00"
  threads: 8
  mem_mb: 122880
  mem_per_cpu: 6144

prealignment_ont_fetch_filtered_reads:
  partition: "core"
  time: "00:15:00"
  threads: 1
  mem_mb: 6144
  mem_per_cpu: 6144

mosdepth:
  partition: "core"
  time: "02:00:00"
  threads: 8
  mem_mb: 122880
  mem_per_cpu: 6144

qc_ont_mosdepth_overlap:
  partition: "core"
  time: "02:00:00"
  threads: 1
  mem_mb: 6144
  mem_per_cpu: 6144

qc_ont_mosdepth_overlap_timestep:
  partition: "core"
  time: "02:00:00"
  threads: 1
  mem_mb: 6144
  mem_per_cpu: 6144

qc_ont_pycoqc:
  partition: "core"
  time: "01:00:00"
  threads: 1
  mem_mb: 6144
  mem_per_cpu: 6144

qc_ont_sequali:
  partition: "core"
  time: "00:05:00"
  threads: 10
  mem_mb: 61440
  mem_per_cpu: 6144

picard_collect_alignment_summary_metrics:
  partition: "core"
  time: "01:00:00"
  threads: 8
  mem_mb: 49152
  mem_per_cpu: 6144

picard_collect_hs_metrics:
  partition: "core"
  time: "01:00:00"
  threads: 8
  mem_mb: 49152
  mem_per_cpu: 6144

snv_indels_svs_clairs_to:
  partition: "core"
  time: "00:45:00"
  threads: 40
  mem_mb: 245760
  mem_per_cpu: 6144

snv_indels_svs_deepsomatic:
  partition: "core"
  time: "00:45:00"
  threads: 40
  mem_mb: 245760
  mem_per_cpu: 6144

snv_indels_svs_savana:
  partition: "core"
  time: "00:45:00"
  threads: 40
  mem_mb: 245760
  mem_per_cpu: 6144
