default_resources:
  threads: 1
  time: "1:00:00"
  mem_mb: 1024
  mem_per_cpu: 1024
  partition: "low"

reference_rules_snv_indels_vardict_gvcf:
  partition: "low"
  time: "72:00:00"
  threads: 2
  mem_mb: 12288
  mem_per_cpu: 6144