$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  output:
    type: string
    description: output yaml/json file defining expected output from pipeline
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  alignment_ont_bam_index:
    type: object
    description: parameters for alignment_ont_bam_index
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  alignment_ont_bam_softclip:
    type: object
    description: parameters for alignment_ont_bam_softclip
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  alignment_ont_bam_sort:
    type: object
    description: parameters for alignment_ont_bam_sort
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  alignment_ont_dorado_align:
    type: object
    description: parameters for alignment_ont_dorado_align
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  alignment_ont_split_bam_by_target:
    type: object
    description: parameters for alignment_ont_dorado_align
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  alignment_ont_split_bam_target_j3:
    type: object
    description: parameters for alignment_ont_split_bam_target_j3
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  basecalling_bam_to_fastq:
    type: object
    description: parameters for basecalling_bam_to_fastq
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  basecalling_compress_fastq:
    type: object
    description: parameters for basecalling_compress_fastq
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  basecalling_dorado_basecaller:
    type: object
    description: parameters for basecalling_dorado_basecaller
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  basecalling_dorado_demux:
    type: object
    description: parameters for basecalling_dorado_demux
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  basecalling_dorado_duplex:
    type: object
    description: parameters for basecalling_dorado_duplex
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  basecalling_dorado_duplex_multisamples:
    type: object
    description: parameters for basecalling_dorado_duplex_multisamples
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  basecalling_dorado_trim:
    type: object
    description: parameters for basecalling_dorado_trim
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  basecalling_rename_demux_bam:
    type: object
    description: parameters for basecalling_rename_demux_bam
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  prealignment_ont_filtlong:
    type: object
    description: parameters for prealignment_ont_filtlong
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  prealignment_ont_fetch_filtered_reads:
    type: object
    description: parameters for prealignment_ont_fetch_filtered_reads
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  prealignment_ont_fetch_too_short_too_long_reads:
    type: object
    description: parameters for prealignment_ont_fetch_too_short_too_long_reads
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

required:
  - samples
  - units
  - output
  - resources
  - default_container

